FROM python:3.11-slim

# Install system utilities needed for image reading tools (like OpenCV/ZBar)
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.full \
    zbar-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app
